#!/bin/bash
#
# Run-level Startup script for webogram
#
# chkconfig: 345 91 19
# description: Startup/Shutdown webogram service

WEBOGRAM_HOMEDIR="/opt/webogram"
WEBOGRAM_BIN="${WEBOGRAM_HOMEDIR}/bin/webogram"
WEBOGRAM_PATH="${WEBOGRAM_HOMEDIR}/git"
WEBOGRAM_PIDFILE="/var/run/webogram.pid"
WEBOGRAM_LOGFILE="/var/log/webogram/webogram.log"
WEBOGRAM_USER="webogram"

find_pid_running() {
  local PID=""
  for PID in $(ps -o pid -d| tr '\n' ' '); do
    if [ "${PID}" == "${1}" ]; then
      echo "TRUE"
      return 0
    fi
  done
  echo "FALSE"
  return 1
}

if [ ! -d ${WEBOGRAM_GITDIR} ]; then
  echo "webogram folder (${WEBOGRAM_GITDIR}) not available: exiting"
  exit 2
elif [ ! -d ${WEBOGRAM_LOGDIR} ]; then
  echo "webogram logfolder (${WEBOGRAM_LOGDIR}) not avilable: exiting"
  exit 3
fi

case "$1" in
  start)
    echo -n "Starting webogram: "
    if [ -f ${WEBOGRAM_PIDFILE} ]; then
      if [ "$(find_pid_running $(cat ${WEBOGRAM_PIDFILE}))" == "TRUE" ]; then
        echo "already running (PID $(cat ${WEBOGRAM_PIDFILE}))"
        exit 4
      else
        echo "crashed. Manually remove ${WEBOGRAM_PIDFILE} and retry"
        exit 5
      fi
    fi
    echo $(su -c "${WEBOGRAM_BIN} -p ${WEBOGRAM_PATH} -l ${WEBOGRAM_LOGFILE}" -l ${WEBOGRAM_USER}) > ${WEBOGRAM_PIDFILE}
    if [ "$(find_pid_running $(cat ${WEBOGRAM_PIDFILE}))" == "TRUE" ]; then
      echo "OK"
    else
      echo "There were problems starting webogram: exiting"
    fi
    ;;
  stop)
    echo -n "Shutdown webogram: "
    kill "$(cat ${WEBOGRAM_PIDFILE})"
    if [ $? -eq 0 ]; then
      rm -f ${WEBOGRAM_PIDFILE}
      echo "OK"
    else
      echo "There were problems stopping webogram: exiting"
      exit -1
    fi
    ;;
  reload|restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 start|stop|restart|reload"
    exit -2
    ;;
esac
exit 0
